platform :ios, '9.0'

target 'movieapp' do
  use_frameworks!

  pod 'SwiftGen', '~> 5.2.1'
  pod 'Swinject', '~> 2.1.1'
  pod 'Alamofire', '~> 4.5.1'
  pod 'Marshal', '~> 1.2.4'
  pod 'SwiftKeychainWrapper', '~> 3.0.1'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'SwiftyJSON'
  pod 'lottie-ios'

end
